local _, UUF = ...

local Defaults = {
    global = {
        UseGlobalProfile = false,
        GlobalProfile = "Default",
        GlobalProfileName = "Default",
        DisplayLoginMessage = false,
    },
    profile = {
        General = {
            TagUpdateInterval = 0.33333333333333,
            Separator = "•",
            ToTSeparator = "»",
            UseCustomAbbreviations = true,
            UIScale = {
                Enabled = true,
                Scale = 0.53333333333333,
            },
            Textures = {
                Foreground = "Better Blizzard",
                Background = "Better Blizzard",
            },
            Range = {
                Enabled = true,
                InRange = 1,
                OutOfRange = 0.5,
            },
            CooldownText = {
                Advanced = false,
                Layout = {"CENTER", "CENTER", 0, 0},
                FontSize = 12,
                ScaleByIconSize = false,
                CooldownBreakpoints = {
                    {threshold = 0, displayStyle = "decimalSeconds", step = 0.1, rounding = 1, format = "%.1f", color = {1, 0.25098040699959, 0.25098040699959, 1}},
                    {threshold = 3, displayStyle = "secondsOnly", step = 1, rounding = 1, min = 1, format = "%d", color = {1, 1, 1, 1}},
                    {threshold = 60, displayStyle = "clock", step = 1, rounding = 1, format = "%d:%02d", color = {1, 1, 1, 1}, components = {{div = 60}, {mod = 60}}},
                    {threshold = 120, displayStyle = "minutes", step = 1, rounding = 1, format = "%dm", color = {1, 1, 1, 1}, components = {{div = 60}}},
                    {threshold = 3600, displayStyle = "hours", step = 1, rounding = 1, format = "%dh", color = {1, 1, 1, 1}, components = {{div = 3600}}},
                },
            },
            Fonts = {
                Font = "Friz Quadrata TT",
                FontFlag = "OUTLINE, SLUG",
                Shadow = {
                    Enabled = false,
                    Colour = {0, 0, 0, 1},
                    XPos = 0,
                    YPos = 0,
                }
            },
            Colours = {
                Reaction = {
                    [1] = {1, 0.25098040699959, 0.25098040699959},            -- Hated
                    [2] = {1, 0.25098040699959, 0.25098040699959},            -- Hostile
                    [3] = {1, 0.50196081399918, 0.25098040699959},           -- Unfriendly
                    [4] = {1, 1, 0.25098040699959},           -- Neutral
                    [5] = {0.25098040699959, 1, 0.25098040699959},            -- Friendly
                    [6] = {0.25098040699959, 1, 0.25098040699959},            -- Honored
                    [7] = {0.25098040699959, 1, 0.25098040699959},            -- Revered
                    [8] = {0.25098040699959, 1, 0.25098040699959},            -- Exalted
                },
                Power = {
                    [0] = {0.25098040699959, 0.50196081399918, 1},                    -- Mana
                    [1] = {1, 0, 0},                    -- Rage
                    [2] = {1, 0.5, 0.25},               -- Focus
                    [3] = {1, 1, 0},                    -- Energy
                    [6] = {0, 0.82, 1},                 -- Runic Power
                    [8] = {0.75, 0.52, 0.9},            -- Lunar Power (Astral Power)
                    [11] = {0, 0.5, 1},                 -- Maelstrom
                    [13] = {0.4, 0, 0.8},               -- Insanity
                    [17] = {0.79, 0.26, 0.99},          -- Fury
                    [18] = {1, 0.61, 0},                -- Pain
                },
                SecondaryPower = {
                    [4] = {1, 0.96, 0.41},              -- Combo Points
                    [5] = {0.5, 0.5, 0.5},              -- Runes
                    [7] = {0.58, 0.51, 0.79},           -- Soul Shards
                    [9] = {0.95, 0.9, 0.6},             -- Holy Power
                    [12] = {0.71, 1, 0.92},             -- Chi
                    [16] = {0.41, 0.8, 0.94},           -- Arcane Charges
                    [19] = {0.3921568627451, 0.67843137254902, 0.8078431372549}, -- Essence
                },
                Dispel = {
                    ["Magic"] = {0.2, 0.6, 1 },
                    ["Curse"] = {0.6, 0, 1 },
                    ["Disease"] = {0.6, 0.4, 0 },
                    ["Poison"] = {0, 0.6, 0 },
                    ["Bleed"] = {0.6, 0, 0.1 }
                },
                Status = {
                    Tapped = {0.6, 0.6, 0.6},
                    Disconnected = {0.6, 0.6, 0.6},
                    DeadBackdrop = {1, 0.25, 0.25},
                },
                Threat = {
                    [0] = {0.69, 0.69, 0.69},
                    [1] = {1, 1, 0.47},
                    [2] = {1, 0.6, 0},
                    [3] = {1, 0, 0},
                }
            }
        },
        Units = {
            player = {
                Enabled = true,
                ForceHideBlizzard = true,
                Frame = {
                    Width = 272,
                    Height = 42,
                    Layout = {"RIGHT", "LEFT", -20, 0},
                    FrameStrata = "LOW",
                },
                HealthBar = {
                    ColourByClass = true,
                    ColourBackgroundByClass = false,
                    ColourByReaction = true,
                    ColourWhenTapped = true,
                    ColourWhenDisconnected = true,
                    AnchorToCooldownViewer = true,
                    Inverse = false,
                    Smooth = false,
                    Foreground = {0.10196079313755, 0.10196079313755, 0.10196079313755},
                    ForegroundOpacity = 1,
                    Background = {0.078431375324726, 0.078431375324726, 0.078431375324726},
                    BackgroundOpacity = 1,
                    DispelHighlight = {
                        Enabled = true,
                        Style = "HEALTHBAR",
                    },
                },
                HealPrediction = {
                    IncomingHeal = {
                        Enabled = false,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.25098039215686, 1, 0.25098039215686, 1},
                        Position = "RIGHT",
                        Height = 40,
                    },
                    Absorbs = {
                        Enabled = true,
                        ShowOverAbsorb = true,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.50196081399918, 0.75294125080109, 1, 0.80000001192093},
                        Position = "ATTACH",
                        Height = 40,
                    },
                    HealAbsorbs = {
                        Enabled = true,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.50196078431373, 0.25098039215686, 1, 1},
                        Position = "ATTACH",
                        Height = 40,
                    },
                },
                PowerBar = {
                    Enabled = false,
                    Height = 3,
                    Foreground = {0.031372549019608, 0.031372549019608, 0.031372549019608},
                    Background = {0.50196078431373, 0.50196078431373, 0.50196078431373},
                    ColourByType = true,
                    ColourBackgroundByType = false,
                    ColourByClass = false,
                    Smooth = true,
                    Inverse = false,
                    Position = "BOTTOM",
                    BackgroundMultiplier = 0.75,
                },
                SecondaryPowerBar = {
                    Enabled = false,
                    Height = 3,
                    Position = "TOP",
                    ColourByType = true,
                    Foreground = {0.031372549019608, 0.031372549019608, 0.031372549019608},
                    Background = {0.50196078431373, 0.50196078431373, 0.50196078431373},
                },
                AlternativePowerBar = {
                    Enabled = false,
                    Height = 5,
                    Width = 100,
                    Foreground = {0.031372549019608, 0.031372549019608, 0.031372549019608},
                    Background = {0.13333333333333, 0.13333333333333, 0.13333333333333},
                    ColourByType = true,
                    Inverse = false,
                    Layout = {"LEFT", "BOTTOMLEFT", 3, 1},
                },
                CastBar = {
                    Enabled = false,
                    Width = 244,
                    Height = 24,
                    Layout = {"TOPLEFT", "BOTTOMLEFT", 0, -1},
                    Foreground = {0.50196078431373, 0.50196078431373, 1},
                    Background = {0.13333333333333, 0.13333333333333, 0.13333333333333},
                    NotInterruptibleColour = {1, 0.25098039215686, 0.25098039215686},
                    InterruptCooldownColour = {0.80000007152557, 0.80000007152557, 0.80000007152557},
                    InterruptedFailedColour = {0.25098039215686, 1, 0.25098039215686},
                    MatchParentWidth = true,
                    ColourByClass = false,
                    Inverse = false,
                    HoldTime = 0.5,
                    ShowTarget = false,
                    FrameStrata = "MEDIUM",
                    Icon = {
                        Enabled = true,
                        Position = "LEFT",
                    },
                    Text = {
                        SpellName = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"LEFT", "LEFT", 3, 0},
                            Colour = {1, 1, 1},
                            MaxChars = 15,
                        },
                        Duration = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"RIGHT", "RIGHT", -3, 0},
                            Colour = {1, 1, 1},
                        }
                    }
                },
                Portrait = {
                    Enabled = false,
                    Width = 42,
                    Height = 42,
                    Layout = {"RIGHT", "LEFT", -1, 0},
                    Zoom = 0.3,
                    UseClassPortrait = false,
                    Style = "2D",
                },
                Indicators = {
                    RaidTargetMarker = {
                        Enabled = true,
                        Size = 24,
                        Layout = {"CENTER", "CENTER", 0, 0},
                    },
                    LeaderAssistantIndicator = {
                        Enabled = false,
                        Size = 16,
                        Layout = {"TOPLEFT", "TOPLEFT", 3, -3},
                    },
                    Resting = {
                        Enabled = false,
                        Size = 16,
                        Layout = {"LEFT", "TOPLEFT", 3, 0},
                        Texture = "RESTING0"
                    },
                    Combat = {
                        Enabled = false,
                        Size = 16,
                        Layout = {"CENTER", "TOP", 0, 0},
                        Texture = "COMBAT0"
                    },
                    PvP = {
                        Enabled = false,
                        Size = 24,
                        Layout = {"RIGHT", "TOPRIGHT", -3, 0},
                    },
                    Mouseover = {
                        Enabled = true,
                        Colour = {1, 1, 1},
                        HighlightOpacity = 1,
                        Style = "BORDER"
                    },
                    Threat = {
                        Enabled = false,
                    },
                    Totems = {
                        Enabled = false,
                        Size = 42,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        GrowthDirection = "LEFT",
                    },
                },
                Auras = {
                    FrameStrata = "LOW",
                    AuraDuration = {
                        Layout = {"CENTER", "CENTER", 0, 0},
                        FontSize = 12,
                        ScaleByIconSize = false,
                    },
                    PrivateAuras = {
						AnchorParent = "Frame",
                        Enabled = true,
                        Layout = {"BOTTOMRIGHT", "TOPRIGHT", 0, 132},
                        FrameStrata = "MEDIUM",
                        Size = 48,
                        Spacing = 1,
                        GrowthX = "LEFT",
                        GrowthY = "UP",
                        InitialAnchor = "BOTTOMRIGHT",
                        Num = 6,
                        BorderScale = -1,
                        DisableCooldown = false,
                        DisableCooldownText = false,
                    },
                    Buffs = {
						AnchorParent = "Frame",
                        Enabled = true,
                        OnlyShowPlayer = false,
                        Size = 42,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                    Debuffs = {
						AnchorParent = "Frame",
                        Enabled = true,
                        OnlyShowPlayer = false,
                        Size = 48,
                        Layout = {"BOTTOMRIGHT", "TOPRIGHT", 0, 83, 1},
                        Num = 6,
                        Wrap = 6,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = true,
                        Filter = "HARMFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                    Custom = {
						AnchorParent = "Frame",
                        Enabled = false,
                        Type = "Buffs",
                        OnlyShowPlayer = false,
                        Size = 42,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                },
                Tags = {
                    TagOne = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagTwo = {
                        FontSize = 12,
                        Layout = {"RIGHT", "RIGHT", -3, 0},
                        Colour = {1, 1, 1},
                        Tag = "[curhpperhp:abbr]",
                    },
                    TagThree = {
                        FontSize = 12,
                        Layout = {"RIGHT", "BOTTOMRIGHT", -3, 2},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagFour = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagFive = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                }
            },
            target = {
                Enabled = true,
                ForceHideBlizzard = true,
                Frame = {
                    Width = 272,
                    Height = 42,
                    Layout = {"LEFT", "RIGHT", 20, 0},
                    FrameStrata = "LOW",
                },
                HealthBar = {
                    ColourByClass = true,
                    ColourBackgroundByClass = false,
                    ColourByReaction = true,
                    ColourWhenTapped = true,
                    ColourWhenDisconnected = true,
                    AnchorToCooldownViewer = true,
                    Inverse = false,
                    Smooth = false,
                    Foreground = {0.10196079313755, 0.10196079313755, 0.10196079313755},
                    ForegroundOpacity = 1,
                    Background = {0.078431375324726, 0.078431375324726, 0.078431375324726},
                    BackgroundOpacity = 1,
                    DispelHighlight = {
                        Enabled = true,
                        Style = "HEALTHBAR",
                    },
                },
                HealPrediction = {
                    IncomingHeal = {
                        Enabled = false,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.25098039215686, 1, 0.25098039215686, 1},
                        Position = "RIGHT",
                        Height = 40,
                    },
                    Absorbs = {
                        Enabled = true,
                        ShowOverAbsorb = true,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.50196081399918, 0.75294125080109, 1, 0.80000007152557},
                        Position = "ATTACH",
                        Height = 40,
                    },
                    HealAbsorbs = {
                        Enabled = true,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.50196078431373, 0.25098039215686, 1, 1},
                        Position = "ATTACH",
                        Height = 40,
                    },
                },
                PowerBar = {
                    Enabled = true,
                    Height = 1,
                    Foreground = {0.031372549019608, 0.031372549019608, 0.031372549019608},
                    Background = {0.50196078431373, 0.50196078431373, 0.50196078431373},
                    ColourByType = true,
                    ColourBackgroundByType = true,
                    ColourByClass = false,
                    Smooth = true,
                    Inverse = false,
                    BackgroundMultiplier = 0.25,
                },
                CastBar = {
                    Enabled = true,
                    Width = 244,
                    Height = 24,
                    Layout = {"TOPLEFT", "BOTTOMLEFT", 0, -1},
                    Foreground = {0.50196078431373, 0.50196078431373, 1},
                    Background = {0.10196079313755, 0.10196079313755, 0.10196079313755},
                    NotInterruptibleColour = {1, 0.25098039215686, 0.25098039215686},
                    InterruptCooldownColour = {0.80000007152557, 0.80000007152557, 0.80000007152557},
                    InterruptedFailedColour = {0.25098039215686, 1, 0.25098039215686},
                    MatchParentWidth = true,
                    ColourByClass = false,
                    Inverse = false,
                    HoldTime = 0.5,
                    ShowTarget = true,
                    FrameStrata = "MEDIUM",
                    Icon = {
                        Enabled = true,
                        Position = "LEFT",
                    },
                    Text = {
                        SpellName = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"LEFT", "LEFT", 3, 0},
                            Colour = {1, 1, 1},
                            MaxChars = 15,
                        },
                        Duration = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"RIGHT", "RIGHT", -3, 0},
                            Colour = {1, 1, 1},
                        }
                    }
                },
                Portrait = {
                    Enabled = false,
                    Width = 42,
                    Height = 42,
                    Layout = {"LEFT", "RIGHT", 1, 0},
                    Zoom = 0.3,
                    UseClassPortrait = false,
                    Style = "2D",
                },
                Indicators = {
                    RaidTargetMarker = {
                        Enabled = true,
                        Size = 24,
                        Layout = {"CENTER", "CENTER", 0, 0},
                    },
                    LeaderAssistantIndicator = {
                        Enabled = false,
                        Size = 16,
                        Layout = {"TOPRIGHT", "TOPRIGHT", -3, -3},
                    },
                    Combat = {
                        Enabled = false,
                        Size = 16,
                        Layout = {"CENTER", "TOP", 0, 0},
                        Texture = "COMBAT0"
                    },
                    Mouseover = {
                        Enabled = true,
                        Colour = {1, 1, 1},
                        HighlightOpacity = 1,
                        Style = "BORDER"
                    },
                    Target = {
                        Enabled = false,
                        Style = "Border",
                        Colour = {1, 1, 1},
                    },
                    Threat = {
                        Enabled = false,
                    },
                    Classification = {
                        Enabled = true,
                        Size = 24,
                        Layout = {"RIGHT", "TOPRIGHT", -3, 0},
                        Texture = "CLASSIFICATION2",
                    },
                    Quest = {
                        Enabled = true,
                        Size = 16,
                        Layout = {"TOPLEFT", "TOPLEFT", 3, -3},
                        Texture = "DEFAULT",
                    },
                },
                Range = {
                    Enabled = true,
                    InRange = 1,
                    OutOfRange = 0.5,
                },
                Auras = {
                    FrameStrata = "LOW",
                    AuraDuration = {
                        Layout = {"CENTER", "CENTER", 0, 0},
                        FontSize = 12,
                        ScaleByIconSize = false,
                    },
                    Buffs = {
						AnchorParent = "Frame",
                        Enabled = true,
                        OnlyShowPlayer = false,
                        Size = 38,
                        Layout = {"BOTTOMLEFT", "TOPLEFT", 0, 1, 1},
                        Num = 7,
                        Wrap = 7,
                        GrowthDirection = "RIGHT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                    Debuffs = {
						AnchorParent = "Frame",
                        Enabled = false,
                        OnlyShowPlayer = false,
                        Size = 34,
                        Layout = {"BOTTOMRIGHT", "TOPRIGHT", 0, 1, 1},
                        Num = 4,
                        Wrap = 4,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HARMFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                    Custom = {
						AnchorParent = "Frame",
                        Enabled = false,
                        Type = "Buffs",
                        OnlyShowPlayer = false,
                        Size = 42,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                },
                Tags = {
                    TagOne = {
                        FontSize = 12,
                        Layout = {"LEFT", "LEFT", 3, 0},
                        Colour = {1, 1, 1},
                        Tag = "[name]",
                    },
                    TagTwo = {
                        FontSize = 12,
                        Layout = {"RIGHT", "RIGHT", -3, 0},
                        Colour = {1, 1, 1},
                        Tag = "[curhpperhp:abbr]",
                    },
                    TagThree = {
                        FontSize = 12,
                        Layout = {"RIGHT", "BOTTOMRIGHT", -3, 2},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagFour = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagFive = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                }
            },
            targettarget = {
                Enabled = false,
                ForceHideBlizzard = true,
                Frame = {
                    Width = 122,
                    Height = 22,
                    AnchorParent = "UUF_Target",
                    Layout = {"TOPRIGHT", "BOTTOMRIGHT", 0, -26.1},
                    FrameStrata = "LOW",
                },
                HealthBar = {
                    ColourByClass = true,
                    ColourBackgroundByClass = false,
                    ColourByReaction = true,
                    ColourWhenTapped = true,
                    ColourWhenDisconnected = true,
                    Inverse = false,
                    Smooth = false,
                    Foreground = {0.10196079313755, 0.10196079313755, 0.10196079313755},
                    ForegroundOpacity = 1,
                    Background = {0.078431375324726, 0.078431375324726, 0.078431375324726},
                    BackgroundOpacity = 1,
                },
                HealPrediction = {
                    IncomingHeal = {
                        Enabled = false,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.25098039215686, 1, 0.25098039215686, 1},
                        Position = "RIGHT",
                        Height = 40,
                    },
                    Absorbs = {
                        Enabled = true,
                        ShowOverAbsorb = false,
                        UseStripedTexture = true,
                        MatchParentHeight = true,
                        Colour = {1, 0.8, 0, 1},
                        Position = "LEFT",
                        Height = 20,
                    },
                    HealAbsorbs = {
                        Enabled = true,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.50196078431373, 0.25098039215686, 1, 1},
                        Position = "RIGHT",
                        Height = 20,
                    },
                },
                PowerBar = {
                    Enabled = false,
                    Height = 3,
                    Foreground = {0.031372549019608, 0.031372549019608, 0.031372549019608},
                    Background = {0.50196078431373, 0.50196078431373, 0.50196078431373},
                    ColourByType = true,
                    ColourBackgroundByType = false,
                    ColourByClass = false,
                    Smooth = true,
                    Inverse = false,
                    BackgroundMultiplier = 0.75,
                },
                Portrait = {
                    Enabled = false,
                    Width = 22,
                    Height = 22,
                    Layout = {"RIGHT", "LEFT", -1, 0},
                    Zoom = 0.3,
                    UseClassPortrait = false,
                    Style = "2D",
                },
                Indicators = {
                    RaidTargetMarker = {
                        Enabled = true,
                        Size = 16,
                        Layout = {"LEFT", "TOPLEFT", 3, 0},
                    },
                    Mouseover = {
                        Enabled = true,
                        Colour = {1, 1, 1},
                        HighlightOpacity = 1,
                        Style = "BORDER"
                    },
                    Target = {
                        Enabled = false,
                        Style = "Glow",
                        Colour = {1, 1, 1},
                    }
                },
                Auras = {
                    FrameStrata = "LOW",
                    AuraDuration = {
                        Layout = {"CENTER", "CENTER", 0, 0},
                        FontSize = 12,
                        ScaleByIconSize = false,
                    },
                    Buffs = {
						AnchorParent = "Frame",
                        Enabled = false,
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                    Debuffs = {
						AnchorParent = "Frame",
                        Enabled = false,
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"LEFT", "RIGHT", 1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "RIGHT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HARMFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                },
                Tags = {
                    TagOne = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "[name]",
                    },
                    TagTwo = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER",0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagThree = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER",0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagFour = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagFive = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                }
            },
            focus = {
                Enabled = true,
                ForceHideBlizzard = true,
                Frame = {
                    Width = 180,
                    Height = 28,
                    AnchorParent = "UUF_Player",
                    Layout = {"BOTTOM", "TOPLEFT", 0, 110.1},
                    FrameStrata = "LOW",
                },
                HealthBar = {
                    ColourByClass = true,
                    ColourBackgroundByClass = false,
                    ColourByReaction = true,
                    ColourWhenTapped = true,
                    ColourWhenDisconnected = true,
                    Inverse = false,
                    Smooth = false,
                    Foreground = {0.10196079313755, 0.10196079313755, 0.10196079313755},
                    ForegroundOpacity = 1,
                    Background = {0.078431375324726, 0.078431375324726, 0.078431375324726},
                    BackgroundOpacity = 1,
                    DispelHighlight = {
                        Enabled = false,
                        Style = "GRADIENT",
                    },
                },
                HealPrediction = {
                    IncomingHeal = {
                        Enabled = false,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.25098039215686, 1, 0.25098039215686, 1},
                        Position = "RIGHT",
                        Height = 40,
                    },
                    Absorbs = {
                        Enabled = false,
                        ShowOverAbsorb = false,
                        UseStripedTexture = true,
                        MatchParentHeight = true,
                        Colour = {1, 0.8, 0, 1},
                        Position = "LEFT",
                        Height = 20,
                    },
                    HealAbsorbs = {
                        Enabled = false,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.50196078431373, 0.25098039215686, 1, 1},
                        Position = "RIGHT",
                        Height = 20,
                    },
                },
                PowerBar = {
                    Enabled = false,
                    Height = 3,
                    Foreground = {0.031372549019608, 0.031372549019608, 0.031372549019608},
                    Background = {0.50196078431373, 0.50196078431373, 0.50196078431373},
                    ColourByType = true,
                    ColourBackgroundByType = false,
                    ColourByClass = false,
                    Smooth = true,
                    Inverse = false,
                    BackgroundMultiplier = 0.75,
                },
                CastBar = {
                    Enabled = false,
                    Width = 244,
                    Height = 24,
                    Layout = {"BOTTOMLEFT", "TOPLEFT", 0, 1},
                    Foreground = {0.50196078431373, 0.50196078431373, 1},
                    Background = {0.13333333333333, 0.13333333333333, 0.13333333333333},
                    NotInterruptibleColour = {1, 0.25098039215686, 0.25098039215686},
                    InterruptCooldownColour = {0.80000007152557, 0.80000007152557, 0.80000007152557},
                    InterruptedFailedColour = {0.25098039215686, 1, 0.25098039215686},
                    MatchParentWidth = true,
                    ColourByClass = false,
                    Inverse = false,
                    HoldTime = 0.5,
                    ShowTarget = false,
                    FrameStrata = "MEDIUM",
                    Icon = {
                        Enabled = false,
                        Position = "LEFT",
                    },
                    Text = {
                        SpellName = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"LEFT", "LEFT", 3, 0},
                            Colour = {1, 1, 1},
                            MaxChars = 15,
                        },
                        Duration = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"RIGHT", "RIGHT", -3, 0},
                            Colour = {1, 1, 1},
                        }
                    }
                },
                Portrait = {
                    Enabled = false,
                    Width = 22,
                    Height = 22,
                    Layout = {"LEFT", "RIGHT", 1, 0},
                    Zoom = 0.3,
                    UseClassPortrait = false,
                    Style = "2D",
                },
                Indicators = {
                    RaidTargetMarker = {
                        Enabled = true,
                        Size = 16,
                        Layout = {"RIGHT", "RIGHT", -3, 0},
                    },
                    Mouseover = {
                        Enabled = true,
                        Colour = {1, 1, 1},
                        HighlightOpacity = 1,
                        Style = "BORDER"
                    },
                    Target = {
                        Enabled = true,
                        Style = "Glow",
                        Colour = {1, 1, 1},
                    },
                    Threat = {
                        Enabled = false,
                    }
                },
                Auras = {
                    FrameStrata = "LOW",
                    AuraDuration = {
                        Layout = {"CENTER", "CENTER", 0, 0},
                        FontSize = 12,
                        ScaleByIconSize = false,
                    },
                    Buffs = {
						AnchorParent = "Frame",
                        Enabled = false,
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 1,
                        Wrap = 1,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                    Debuffs = {
						AnchorParent = "Frame",
                        Enabled = false,
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"LEFT", "RIGHT", 1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "RIGHT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HARMFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                    Custom = {
						AnchorParent = "Frame",
                        Enabled = false,
                        Type = "Buffs",
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                },
                Tags = {
                    TagOne = {
                        FontSize = 12,
                        Layout = {"LEFT", "LEFT", 3, 0},
                        Colour = {1, 1, 1},
                        Tag = "[name]",
                    },
                    TagTwo = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER",0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagThree = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER",0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagFour = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagFive = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                }
            },
            focustarget = {
                Enabled = false,
                ForceHideBlizzard = true,
                Frame = {
                    Width = 122,
                    Height = 22,
                    AnchorParent = "UUF_Focus",
                    Layout = {"LEFT", "RIGHT", 1, 0},
                    FrameStrata = "LOW",
                },
                HealthBar = {
                    ColourByClass = true,
                    ColourBackgroundByClass = false,
                    ColourByReaction = true,
                    ColourWhenTapped = true,
                    ColourWhenDisconnected = true,
                    Inverse = false,
                    Smooth = false,
                    Foreground = {0.10196079313755, 0.10196079313755, 0.10196079313755},
                    ForegroundOpacity = 1,
                    Background = {0.078431375324726, 0.078431375324726, 0.078431375324726},
                    BackgroundOpacity = 1,
                },
                HealPrediction = {
                    IncomingHeal = {
                        Enabled = false,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.25098039215686, 1, 0.25098039215686, 1},
                        Position = "RIGHT",
                        Height = 40,
                    },
                    Absorbs = {
                        Enabled = true,
                        ShowOverAbsorb = false,
                        UseStripedTexture = true,
                        MatchParentHeight = true,
                        Colour = {1, 0.8, 0, 1},
                        Position = "LEFT",
                        Height = 20,
                    },
                    HealAbsorbs = {
                        Enabled = true,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.50196078431373, 0.25098039215686, 1, 1},
                        Position = "RIGHT",
                        Height = 20,
                    },
                },
                PowerBar = {
                    Enabled = false,
                    Height = 3,
                    Foreground = {0.031372549019608, 0.031372549019608, 0.031372549019608},
                    Background = {0.50196078431373, 0.50196078431373, 0.50196078431373},
                    ColourByType = true,
                    ColourBackgroundByType = false,
                    ColourByClass = false,
                    Smooth = true,
                    Inverse = false,
                    BackgroundMultiplier = 0.75,
                },
                Portrait = {
                    Enabled = false,
                    Width = 22,
                    Height = 22,
                    Layout = {"RIGHT", "LEFT", -1, 0},
                    Zoom = 0.3,
                    UseClassPortrait = false,
                    Style = "2D",
                },
                Indicators = {
                    RaidTargetMarker = {
                        Enabled = true,
                        Size = 16,
                        Layout = {"LEFT", "TOPLEFT", 3, 0},
                    },
                    Mouseover = {
                        Enabled = true,
                        Colour = {1, 1, 1},
                        HighlightOpacity = 1,
                        Style = "BORDER"
                    },
                    Target = {
                        Enabled = false,
                        Style = "Glow",
                        Colour = {1, 1, 1},
                    }
                },
                Auras = {
                    FrameStrata = "LOW",
                    AuraDuration = {
                        Layout = {"CENTER", "CENTER", 0, 0},
                        FontSize = 12,
                        ScaleByIconSize = false,
                    },
                    Buffs = {
						AnchorParent = "Frame",
                        Enabled = false,
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                    Debuffs = {
						AnchorParent = "Frame",
                        Enabled = false,
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"LEFT", "RIGHT", 1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "RIGHT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HARMFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                },
                Tags = {
                    TagOne = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "[name]",
                    },
                    TagTwo = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER",0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagThree = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER",0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagFour = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagFive = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                }
            },
            pet = {
                Enabled = true,
                ForceHideBlizzard = true,
                Frame = {
                    Width = 265,
                    Height = 3,
                    AnchorParent = "UUF_Player",
                    Layout = {"TOPLEFT", "BOTTOMLEFT", 0, -1},
                    FrameStrata = "LOW",
                },
                HealthBar = {
                    ColourByClass = true,
                    ColourBackgroundByClass = false,
                    ColourByReaction = true,
                    ColourWhenTapped = true,
                    ColourWhenDisconnected = true,
                    Inverse = false,
                    Smooth = false,
                    Foreground = {0.10196079313755, 0.10196079313755, 0.10196079313755},
                    ForegroundOpacity = 1,
                    Background = {0.078431375324726, 0.078431375324726, 0.078431375324726},
                    BackgroundOpacity = 1,
                },
                HealPrediction = {
                    IncomingHeal = {
                        Enabled = false,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.25098039215686, 1, 0.25098039215686, 1},
                        Position = "RIGHT",
                        Height = 40,
                    },
                    Absorbs = {
                        Enabled = false,
                        ShowOverAbsorb = false,
                        UseStripedTexture = true,
                        MatchParentHeight = true,
                        Colour = {1, 0.8, 0, 1},
                        Position = "LEFT",
                        Height = 20,
                    },
                    HealAbsorbs = {
                        Enabled = false,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.50196078431373, 0.25098039215686, 1, 1},
                        Position = "RIGHT",
                        Height = 20,
                    },
                },
                PowerBar = {
                    Enabled = false,
                    Height = 3,
                    Foreground = {0.031372549019608, 0.031372549019608, 0.031372549019608},
                    Background = {0.50196078431373, 0.50196078431373, 0.50196078431373},
                    ColourByType = true,
                    ColourBackgroundByType = false,
                    ColourByClass = false,
                    Smooth = true,
                    Inverse = false,
                    BackgroundMultiplier = 0.75,
                },
                CastBar = {
                    Enabled = false,
                    Width = 244,
                    Height = 24,
                    Layout = {"TOPLEFT", "BOTTOMLEFT", 0, -1},
                    Foreground = {0.50196078431373, 0.50196078431373, 1},
                    Background = {0.13333333333333, 0.13333333333333, 0.13333333333333},
                    NotInterruptibleColour = {1, 0.25098039215686, 0.25098039215686},
                    InterruptCooldownColour = {0.80000007152557, 0.80000007152557, 0.80000007152557},
                    InterruptedFailedColour = {0.25098039215686, 1, 0.25098039215686},
                    MatchParentWidth = true,
                    ColourByClass = false,
                    Inverse = false,
                    HoldTime = 0.5,
                    ShowTarget = false,
                    FrameStrata = "MEDIUM",
                    Icon = {
                        Enabled = false,
                        Position = "LEFT",
                    },
                    Text = {
                        SpellName = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"LEFT", "LEFT", 3, 0},
                            Colour = {1, 1, 1},
                            MaxChars = 15,
                        },
                        Duration = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"RIGHT", "RIGHT", -3, 0},
                            Colour = {1, 1, 1},
                        }
                    }
                },
                Portrait = {
                    Enabled = false,
                    Width = 22,
                    Height = 22,
                    Layout = {"LEFT", "RIGHT", 1, 0},
                    Zoom = 0.3,
                    UseClassPortrait = false,
                    Style = "2D",
                },
                Indicators = {
                    RaidTargetMarker = {
                        Enabled = false,
                        Size = 16,
                        Layout = {"LEFT", "TOPLEFT", 3, 0},
                    },
                    Mouseover = {
                        Enabled = true,
                        Colour = {1, 1, 1},
                        HighlightOpacity = 1,
                        Style = "BORDER"
                    },
                    Target = {
                        Enabled = false,
                        Style = "Glow",
                        Colour = {1, 1, 1},
                    },
                    Threat = {
                        Enabled = false,
                    }
                },
                Auras = {
                    FrameStrata = "LOW",
                    AuraDuration = {
                        Layout = {"CENTER", "CENTER", 0, 0},
                        FontSize = 12,
                        ScaleByIconSize = false,
                    },
                    Buffs = {
						AnchorParent = "Frame",
                        Enabled = false,
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"LEFT", "RIGHT", 1, 0, 1},
                        Num = 1,
                        Wrap = 1,
                        GrowthDirection = "RIGHT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                    Debuffs = {
						AnchorParent = "Frame",
                        Enabled = false,
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HARMFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                    Custom = {
						AnchorParent = "Frame",
                        Enabled = false,
                        Type = "Buffs",
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                },
                Tags = {
                    TagOne = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagTwo = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER",0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagThree = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER",0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagFour = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagFive = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                }
            },
            boss = {
                Enabled = true,
                ForceHideBlizzard = true,
                Frame = {
                    Width = 252,
                    Height = 52,
                    Layout = {"CENTER", "CENTER", 550.1, -0.1, 26},
                    GrowthDirection = "DOWN",
                    FrameStrata = "LOW",
                },
                HealthBar = {
                    ColourByClass = true,
                    ColourBackgroundByClass = false,
                    ColourByReaction = true,
                    ColourWhenTapped = true,
                    ColourWhenDisconnected = true,
                    Inverse = false,
                    Smooth = false,
                    Foreground = {0.10196079313755, 0.10196079313755, 0.10196079313755},
                    ForegroundOpacity = 1,
                    Background = {0.078431375324726, 0.078431375324726, 0.078431375324726},
                    BackgroundOpacity = 1,
                },
                HealPrediction = {
                    IncomingHeal = {
                        Enabled = false,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.25098039215686, 1, 0.25098039215686, 1},
                        Position = "RIGHT",
                        Height = 40,
                    },
                    Absorbs = {
                        Enabled = true,
                        ShowOverAbsorb = true,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.50196081399918, 0.75294125080109, 1, 0.80000007152557},
                        Position = "ATTACH",
                        Height = 40,
                    },
                    HealAbsorbs = {
                        Enabled = true,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.50196078431373, 0.25098039215686, 1, 1},
                        Position = "ATTACH",
                        Height = 40,
                    },
                },
                PowerBar = {
                    Enabled = true,
                    Height = 1,
                    Foreground = {0.031372549019608, 0.031372549019608, 0.031372549019608},
                    Background = {0.50196078431373, 0.50196078431373, 0.50196078431373},
                    ColourByType = true,
                    ColourBackgroundByType = true,
                    ColourByClass = false,
                    Smooth = true,
                    Inverse = false,
                    BackgroundMultiplier = 0.25,
                },
                CastBar = {
                    Enabled = true,
                    Width = 244,
                    Height = 24,
                    Layout = {"TOPLEFT", "BOTTOMLEFT", 0, -1},
                    Foreground = {0.50196078431373, 0.50196078431373, 1},
                    Background = {0.13333333333333, 0.13333333333333, 0.13333333333333},
                    NotInterruptibleColour = {1, 0.25098039215686, 0.25098039215686},
                    InterruptCooldownColour = {0.80000007152557, 0.80000007152557, 0.80000007152557},
                    InterruptedFailedColour = {0.25098039215686, 1, 0.25098039215686},
                    MatchParentWidth = true,
                    ColourByClass = false,
                    Inverse = false,
                    HoldTime = 0.5,
                    ShowTarget = false,
                    FrameStrata = "MEDIUM",
                    Icon = {
                        Enabled = true,
                        Position = "LEFT",
                    },
                    Text = {
                        SpellName = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"LEFT", "LEFT", 3, 0},
                            Colour = {1, 1, 1},
                            MaxChars = 15,
                        },
                        Duration = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"RIGHT", "RIGHT", -3, 0},
                            Colour = {1, 1, 1},
                        }
                    }
                },
                Portrait = {
                    Enabled = false,
                    Width = 42,
                    Height = 42,
                    Layout = {"RIGHT", "LEFT", -1, 0},
                    Zoom = 0.3,
                    UseClassPortrait = false,
                    Style = "2D",
                },
                Indicators = {
                    RaidTargetMarker = {
                        Enabled = true,
                        Size = 24,
                        Layout = {"CENTER", "CENTER", 0, 0},
                    },
                    Mouseover = {
                        Enabled = true,
                        Colour = {1, 1, 1},
                        HighlightOpacity = 1,
                        Style = "BORDER"
                    },
                    Target = {
                        Enabled = true,
                        Style = "Glow",
                        Colour = {1, 1, 1},
                    }
                },
                Auras = {
                    FrameStrata = "LOW",
                    AuraDuration = {
                        Layout = {"CENTER", "CENTER", 0, 0},
                        FontSize = 12,
                        ScaleByIconSize = false,
                    },
                    Buffs = {
						AnchorParent = "Frame",
                        Enabled = true,
                        OnlyShowPlayer = false,
                        Size = 52,
                        Layout = {"LEFT", "RIGHT", 1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "RIGHT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                    Debuffs = {
						AnchorParent = "Frame",
                        Enabled = false,
                        OnlyShowPlayer = false,
                        Size = 34,
                        Layout = {"BOTTOMRIGHT", "TOPRIGHT", 0, 1, 1},
                        Num = 4,
                        Wrap = 4,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HARMFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                    Custom = {
						AnchorParent = "Frame",
                        Enabled = false,
                        Type = "Buffs",
                        OnlyShowPlayer = false,
                        Size = 42,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                },
                Tags = {
                    TagOne = {
                        FontSize = 12,
                        Layout = {"LEFT", "LEFT", 3, 0},
                        Colour = {1, 1, 1},
                        Tag = "[name]",
                    },
                    TagTwo = {
                        FontSize = 12,
                        Layout = {"RIGHT", "RIGHT", -3, 0},
                        Colour = {1, 1, 1},
                        Tag = "[curhpperhp:abbr]",
                    },
                    TagThree = {
                        FontSize = 12,
                        Layout = {"RIGHT", "BOTTOMRIGHT", -3, 2},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagFour = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagFive = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                }
            },
            party = {
                Enabled = true,
                ForceHideBlizzard = true,
                Frame = {
                    Width = 252,
                    Height = 52,
                    Layout = {"CENTER", "CENTER", -550.1, -0.1, 1},
                    GrowthDirection = "DOWN",
                    SortBy = "ROLE",
                    RoleOrder = {"TANK", "HEALER", "DAMAGER"},
                    ShowPlayer = false,
                    FrameStrata = "LOW",
                },
                HealthBar = {
                    ColourByClass = true,
                    ColourBackgroundByClass = false,
                    ColourByReaction = true,
                    ColourWhenTapped = true,
                    ColourWhenDisconnected = true,
                    ColourBackdropWhenDead = false,
                    Inverse = false,
                    Smooth = false,
                    Foreground = {0.10196079313755, 0.10196079313755, 0.10196079313755},
                    ForegroundOpacity = 1,
                    Background = {0.078431375324726, 0.078431375324726, 0.078431375324726},
                    BackgroundOpacity = 1,
                    DispelHighlight = {
                        Enabled = true,
                        Style = "HEALTHBAR",
                    },
                },
                HealPrediction = {
                    IncomingHeal = {
                        Enabled = false,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.25098039215686, 1, 0.25098039215686, 1},
                        Position = "RIGHT",
                        Height = 40,
                    },
                    Absorbs = {
                        Enabled = true,
                        ShowOverAbsorb = true,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.50196081399918, 0.75294125080109, 1, 0.80000007152557},
                        Position = "ATTACH",
                        Height = 40,
                    },
                    HealAbsorbs = {
                        Enabled = true,
                        UseStripedTexture = false,
                        MatchParentHeight = false,
                        Colour = {0.50196078431373, 0.25098039215686, 1, 1},
                        Position = "ATTACH",
                        Height = 40,
                    },
                },
                PowerBar = {
                    Enabled = true,
                    OnlyShowHealers = true,
                    Height = 1,
                    Foreground = {0.031372549019608, 0.031372549019608, 0.031372549019608},
                    Background = {0.50196078431373, 0.50196078431373, 0.50196078431373},
                    ColourByType = true,
                    ColourBackgroundByType = true,
                    ColourByClass = false,
                    Smooth = true,
                    Inverse = false,
                    BackgroundMultiplier = 0.25,
                },
                Indicators = {
                    RaidTargetMarker = {
                        Enabled = true,
                        Size = 24,
                        Layout = {"CENTER", "CENTER", 0, 0},
                    },
                    Mouseover = {
                        Enabled = true,
                        Colour = {1, 1, 1},
                        HighlightOpacity = 1,
                        Style = "BORDER"
                    },
                    Target = {
                        Enabled = false,
                        Style = "Glow",
                        Colour = {1, 1, 1},
                    },
                    Threat = {
                        Enabled = false,
                    },
                    Role = {
                        Enabled = true,
						ShowTank = true,
						ShowHealer = true,
						ShowDamager = true,
                        Texture = "White",
                        Size = 16,
                        Layout = {"TOPLEFT", "TOPLEFT", 1, 0},
                    },
                    Phase = {
                        Enabled = false,
                        Size = 16,
                        Layout = {"CENTER", "CENTER", 0, 0},
                    },
                    Summon = {
                        Enabled = true,
                        Size = 24,
                        Layout = {"CENTER", "CENTER", 0, 0},
                    },
					ReadyCheckIndicator = {
						Enabled = true,
						Texture = "HiRes",
						Size = 24,
						Layout = {"CENTER", "CENTER", 0, 0},
					},
					ResurrectIndicator = {
						Enabled = true,
						Size = 24,
						Layout = {"CENTER", "CENTER", 0, 0},
					},
                    LeaderAssistantIndicator = {
                        Enabled = false,
                        Size = 16,
                        Layout = {"RIGHT", "TOPRIGHT", -3, 0},
                    }
                },
                Auras = {
                    FrameStrata = "MEDIUM",
                    AuraDuration = {
                        Layout = {"CENTER", "CENTER", 0, 0},
                        FontSize = 12,
                        ScaleByIconSize = false,
                    },
                    PrivateAuras = {
						AnchorParent = "Frame",
                        Enabled = true,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        FrameStrata = "MEDIUM",
                        Size = 32,
                        Spacing = 1,
                        GrowthX = "LEFT",
                        GrowthY = "UP",
                        InitialAnchor = "CENTER",
                        Num = 1,
                        BorderScale = -1,
                        DisableCooldown = false,
                        DisableCooldownText = false,
                    },
                    Buffs = {
						AnchorParent = "Health",
                        Enabled = true,
                        OnlyShowPlayer = false,
                        Size = 30,
                        Layout = {"BOTTOMLEFT", "BOTTOMLEFT", 1, 1, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "RIGHT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                    Debuffs = {
						AnchorParent = "Health",
                        Enabled = true,
                        OnlyShowPlayer = false,
                        Size = 30,
                        Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", -1, 1, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = true,
                        Filter = "HARMFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                    Custom = {
						AnchorParent = "Frame",
                        Enabled = false,
                        Type = "Buffs",
                        OnlyShowPlayer = false,
                        Size = 42,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                },
                Tags = {
                    TagOne = {
                        FontSize = 12,
                        Layout = {"TOPLEFT", "TOPLEFT", 16, -3},
                        Colour = {1, 1, 1},
                        Tag = "[name]",
                    },
                    TagTwo = {
                        FontSize = 12,
                        Layout = {"TOPRIGHT", "TOPRIGHT", -3, -3},
                        Colour = {1, 1, 1},
                        Tag = "[perhp-with-sign]",
                    },
                    TagThree = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagFour = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagFive = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                }
            },
            raid = {
                Enabled = true,
                ForceHideBlizzard = true,
                Frame = {
                    Width = 90,
                    Height = 52,
                    Layout = {"LEFT", "LEFT", 1.1000000000004, 0.10000000000036, 1},
                    GrowthDirection = "LEFT_DOWN",
                    SortBy = "GROUP",
                    AutoAdjustGroups = false,
                    Groups = {[1] = true, [2] = true, [3] = true, [4] = true, [5] = true, [6] = true, [7] = false, [8] = false},
                    FrameStrata = "LOW",
                },
                HealthBar = {
                    ColourByClass = true,
                    ColourBackgroundByClass = false,
                    ColourByReaction = true,
                    ColourWhenTapped = true,
                    ColourWhenDisconnected = true,
                    ColourBackdropWhenDead = true,
                    Inverse = false,
                    Smooth = false,
                    Foreground = {0.10196079313755, 0.10196079313755, 0.10196079313755},
                    ForegroundOpacity = 1,
                    Background = {0.078431375324726, 0.078431375324726, 0.078431375324726},
                    BackgroundOpacity = 1,
                    DispelHighlight = {
                        Enabled = true,
                        Style = "HEALTHBAR",
                    },
                },
                HealPrediction = {
                    IncomingHeal = {
                        Enabled = false,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.25098039215686, 1, 0.25098039215686, 1},
                        Position = "RIGHT",
                        Height = 40,
                    },
                    Absorbs = {
                        Enabled = true,
                        ShowOverAbsorb = true,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.50196081399918, 0.75294125080109, 1, 0.80000007152557},
                        Position = "ATTACH",
                        Height = 40,
                    },
                    HealAbsorbs = {
                        Enabled = true,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Colour = {0.50196078431373, 0.25098039215686, 1, 1},
                        Position = "ATTACH",
                        Height = 40,
                    },
                },
                PowerBar = {
                    Enabled = true,
                    OnlyShowHealers = true,
                    Height = 1,
                    Foreground = {0.031372549019608, 0.031372549019608, 0.031372549019608},
                    Background = {0.50196078431373, 0.50196078431373, 0.50196078431373},
                    ColourByType = true,
                    ColourBackgroundByType = true,
                    ColourByClass = false,
                    Smooth = true,
                    Inverse = false,
                    BackgroundMultiplier = 0.25,
                },
                Indicators = {
                    RaidTargetMarker = {
                        Enabled = true,
                        Size = 24,
                        Layout = {"CENTER", "CENTER", 0, 0},
                    },
                    Mouseover = {
                        Enabled = true,
                        Colour = {1, 1, 1},
                        HighlightOpacity = 1,
                        Style = "BORDER"
                    },
                    Target = {
                        Enabled = false,
                        Style = "Glow",
                        Colour = {1, 1, 1},
                    },
                    Threat = {
                        Enabled = false,
                    },
                    Role = {
                        Enabled = false,
						ShowTank = true,
						ShowHealer = true,
						ShowDamager = false,
                        Texture = "White",
                        Size = 12,
                        Layout = {"TOPRIGHT", "TOPRIGHT", -3, -3},
                    },
                    Phase = {
                        Enabled = false,
                        Size = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                    },
                    Summon = {
                        Enabled = true,
                        Size = 24,
                        Layout = {"CENTER", "CENTER", 0, 0},
                    },
					ReadyCheckIndicator = {
						Enabled = true,
						Texture = "HiRes",
						Size = 24,
						Layout = {"CENTER", "CENTER", 0, 0},
					},
					ResurrectIndicator = {
						Enabled = true,
						Size = 18,
						Layout = {"CENTER", "CENTER", 0, 0},
					},
                    LeaderAssistantIndicator = {
                        Enabled = false,
                        Size = 14,
                        Layout = {"TOPRIGHT", "TOPRIGHT", -3, -3},
                    }
                },
                Auras = {
                    FrameStrata = "MEDIUM",
                    AuraDuration = {
                        Layout = {"CENTER", "CENTER", 0, 0},
                        FontSize = 12,
                        ScaleByIconSize = false,
                    },
                    PrivateAuras = {
						AnchorParent = "Frame",
                        Enabled = true,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        FrameStrata = "HIGH",
                        Size = 32,
                        Spacing = 1,
                        GrowthX = "LEFT",
                        GrowthY = "UP",
                        InitialAnchor = "CENTER",
                        Num = 1,
                        BorderScale = -1,
                        DisableCooldown = false,
                        DisableCooldownText = false,
                    },
                    Buffs = {
						AnchorParent = "Health",
                        Enabled = true,
                        OnlyShowPlayer = false,
                        Size = 30,
                        Layout = {"BOTTOMLEFT", "BOTTOMLEFT", 1, 1, 1},
                        Num = 1,
                        Wrap = 1,
                        GrowthDirection = "RIGHT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                    Debuffs = {
						AnchorParent = "Health",
                        Enabled = true,
                        OnlyShowPlayer = false,
                        Size = 28,
                        Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", -1, 1, -1},
                        Num = 2,
                        Wrap = 2,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = true,
                        Filter = "HARMFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                    Custom = {
						AnchorParent = "Frame",
                        Enabled = false,
                        Type = "Buffs",
                        OnlyShowPlayer = false,
                        Size = 42,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Colour = {1, 1, 1, 1}
                        }
                    },
                },
                Tags = {
                    TagOne = {
                        FontSize = 12,
                        Layout = {"TOPLEFT", "TOPLEFT", 3, -3},
                        Colour = {1, 1, 1},
                        Tag = "[name]",
                    },
                    TagTwo = {
                        FontSize = 12,
                        Layout = {"TOPRIGHT", "TOPRIGHT", -3, -3},
                        Colour = {1, 1, 1},
                        Tag = "[status]",
                    },
                    TagThree = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagFour = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                    TagFive = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Colour = {1, 1, 1},
                        Tag = "",
                    },
                },
				augmentation = {
					Enabled = false,
					Names = "",
					Frame = {
						Width = 90,
						Height = 52,
						Layout = {"CENTER", "CENTER", 0, 0, 1},
						GrowthDirection = "LEFT_DOWN",
						UnitsPerColumn = 5,
						SortBy = "NAMELIST",
						FrameStrata = "LOW",
					},
					HealthBar = {
                        ColourByClass = true,
                        ColourBackgroundByClass = false,
                        ColourByReaction = true,
                        ColourWhenTapped = true,
                        ColourWhenDisconnected = true,
                        ColourBackdropWhenDead = true,
                        Inverse = false,
                        Smooth = false,
                        Foreground = {0.10196079313755, 0.10196079313755, 0.10196079313755},
                        ForegroundOpacity = 1,
                        Background = {0.078431375324726, 0.078431375324726, 0.078431375324726},
                        BackgroundOpacity = 1,
                        DispelHighlight = {
                            Enabled = true,
                            Style = "HEALTHBAR",
                        },
					},
					HealPrediction = {
                        IncomingHeal = {
                            Enabled = false,
                            UseStripedTexture = false,
                            MatchParentHeight = true,
                            Colour = {0.25098039215686, 1, 0.25098039215686, 1},
                            Position = "RIGHT",
                            Height = 40,
                        },
                        Absorbs = {
                            Enabled = false,
                            ShowOverAbsorb = true,
                            UseStripedTexture = false,
                            MatchParentHeight = true,
                            Colour = {0.50196081399918, 0.75294125080109, 1, 0.80000007152557},
                            Position = "ATTACH",
                            Height = 40,
                        },
                        HealAbsorbs = {
                            Enabled = false,
                            UseStripedTexture = false,
                            MatchParentHeight = true,
                            Colour = {0.50196078431373, 0.25098039215686, 1, 1},
                            Position = "ATTACH",
                            Height = 40,
                        },
					},
					PowerBar = {
						Enabled = false,
						OnlyShowHealers = true,
						Height = 1,
						Foreground = {0.031372549019608, 0.031372549019608, 0.031372549019608},
						Background = {0.50196078431373, 0.50196078431373, 0.50196078431373},
						ColourByType = true,
						ColourBackgroundByType = true,
						ColourByClass = false,
						Smooth = true,
						Inverse = false,
						BackgroundMultiplier = 0.25,
					},
					Indicators = {
						RaidTargetMarker = {
							Enabled = false,
							Size = 24,
							Layout = {"CENTER", "CENTER", 0, 0},
						},
						Mouseover = {
							Enabled = true,
							Colour = {1, 1, 1},
							HighlightOpacity = 0.25,
							Style = "OVERLAY"
						},
						Target = {
							Enabled = false,
							Style = "Glow",
							Colour = {1, 1, 1},
						},
						Threat = {
							Enabled = false,
						},
						Role = {
							Enabled = false,
							ShowTank = true,
							ShowHealer = true,
							ShowDamager = false,
							Texture = "White",
							Size = 12,
							Layout = {"TOPRIGHT", "TOPRIGHT", -3, -3},
						},
						Phase = {
							Enabled = false,
							Size = 12,
							Layout = {"CENTER", "CENTER", 0, 0},
						},
						Summon = {
							Enabled = false,
							Size = 24,
							Layout = {"CENTER", "CENTER", 0, 0},
						},
						ReadyCheckIndicator = {
							Enabled = false,
							Texture = "Default",
							Size = 24,
							Layout = {"CENTER", "CENTER", 0, 0},
						},
						ResurrectIndicator = {
							Enabled = false,
							Size = 18,
							Layout = {"CENTER", "CENTER", 0, 0},
						},
						LeaderAssistantIndicator = {
							Enabled = false,
							Size = 14,
							Layout = {"TOPRIGHT", "TOPRIGHT", -3, -3},
						}
					},
					Auras = {
						FrameStrata = "MEDIUM",
						AuraDuration = {
							Layout = {"CENTER", "CENTER", 0, 0},
							FontSize = 12,
							ScaleByIconSize = false,
						},
						PrivateAuras = {
							AnchorParent = "Frame",
							Enabled = false,
							Layout = {"CENTER", "CENTER", 0, 0},
							FrameStrata = "HIGH",
							Size = 32,
							Spacing = 1,
							GrowthX = "LEFT",
							GrowthY = "UP",
							InitialAnchor = "CENTER",
							Num = 1,
							BorderScale = -1,
							DisableCooldown = false,
							DisableCooldownText = false,
						},
						Buffs = {
							AnchorParent = "Frame",
							Enabled = true,
							OnlyShowPlayer = false,
							Size = 28,
							Layout = {"BOTTOMLEFT", "BOTTOMLEFT", 2, 2, 1},
							Num = 1,
							Wrap = 1,
							GrowthDirection = "RIGHT",
							WrapDirection = "UP",
							ShowType = false,
							Blacklist = false,
							Filter = "HELPFUL",
							Sorting = "BLIZZARD",
							Count = {
								HideStacks = false,
								Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
								FontSize = 12,
								Colour = {1, 1, 1, 1}
							}
						},
						Debuffs = {
							AnchorParent = "Frame",
							Enabled = false,
							OnlyShowPlayer = false,
							Size = 31,
							Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", -2, 2, 1},
							Num = 2,
							Wrap = 2,
							GrowthDirection = "LEFT",
							WrapDirection = "UP",
							ShowType = false,
							Blacklist = true,
							Filter = "HARMFUL",
							Sorting = "BLIZZARD",
							Count = {
								HideStacks = false,
								Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
								FontSize = 12,
								Colour = {1, 1, 1, 1}
							}
						},
						Custom = {
							AnchorParent = "Frame",
							Enabled = false,
							Type = "Buffs",
							OnlyShowPlayer = false,
							Size = 42,
							Layout = {"RIGHT", "LEFT", -1, 0, 1},
							Num = 3,
							Wrap = 3,
							GrowthDirection = "LEFT",
							WrapDirection = "UP",
							ShowType = false,
							Blacklist = false,
							Filter = "HELPFUL",
							Sorting = "BLIZZARD",
							Count = {
								HideStacks = false,
								Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
								FontSize = 12,
								Colour = {1, 1, 1, 1}
							}
						},
					},
					Tags = {
						TagOne = {
							FontSize = 12,
							Layout = {"CENTER", "CENTER", 0, 0},
							Colour = {1, 1, 1},
							Tag = "[name]",
						},
						TagTwo = {
							FontSize = 12,
							Layout = {"CENTER", "CENTER", 0, 0},
							Colour = {1, 1, 1},
							Tag = "",
						},
						TagThree = {
							FontSize = 12,
							Layout = {"CENTER", "CENTER", 0, 0},
							Colour = {1, 1, 1},
							Tag = "",
						},
						TagFour = {
							FontSize = 12,
							Layout = {"CENTER", "CENTER", 0, 0},
							Colour = {1, 1, 1},
							Tag = "",
						},
						TagFive = {
							FontSize = 12,
							Layout = {"CENTER", "CENTER", 0, 0},
							Colour = {1, 1, 1},
							Tag = "",
						},
					}
				},
            },
        }
    },
}

---@return table Defaults Returns the Default Table.
function UUF:GetDefaultDB() return Defaults end
